version: '3.4'
services:
  web:
    build: .
    platform: "linux/amd64"
    image: yigamarkgabriel333288/pharmacy_staging:latest #  Staging/Develop
    container_name: "pharmacy_sys_staging"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8001
    # ports:
    #   - 8001:8001
    env_file:
      - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    image: yigamarkgabriel333288/pharmarcy_staging_nginx:latest
    container_name: "pharmarcy_staging_nginx"
    ports:
      - 81:81
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: