# Generated by Django 3.2.20 on 2024-02-15 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('supplier_type', models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('STORE', 'STORE')], default='SUPPLIER', max_length=10)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(null=True)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_period', models.CharField(choices=[('Instant', 'Instant'), ('After 7 days', 'After 7 days'), ('After 14 days', 'After 14 days'), ('After 30 days', 'After 30 days'), ('After 60 days', 'After 60 days')], default='Instant', max_length=25)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=225, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical purchase order',
                'verbose_name_plural': 'historical purchase orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseOrderItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_by', models.CharField(blank=True, max_length=225, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical purchase order item',
                'verbose_name_plural': 'historical purchase order items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_type', models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('STORE', 'STORE')], default='SUPPLIER', max_length=10)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(null=True)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_period', models.CharField(choices=[('Instant', 'Instant'), ('After 7 days', 'After 7 days'), ('After 14 days', 'After 14 days'), ('After 30 days', 'After 30 days'), ('After 60 days', 'After 60 days')], default='Instant', max_length=25)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('list_purchase_order', 'List purchase order'), ('view_purchase_order', 'View purchase order'), ('add_purchase_order', 'Add purchase order'), ('edit_purchase_order', 'Edit purchase order'), ('approve_purchase_order', 'Approve purchase order'), ('cancel_purchase_order', 'Cancel purchase order'), ('activate_purchase_order', 'Activate purchase order'), ('deactivate_purchase_order', 'Deactivate purchase order'), ('delete_purchase_order', 'Delete purchase order')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_by', models.CharField(blank=True, max_length=225, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('list_purchase_order_item', 'List purchase order item'), ('view_purchase_order_item', 'View purchase order item'), ('add_purchase_order_item', 'Add purchase order item'), ('edit_purchase_order_item', 'Edit purchase order item'), ('approve_purchase_order_item', 'Approve purchase order item'), ('cancel_purchase_order_item', 'Cancel purchase order item'), ('activate_purchase_order_item', 'Activate purchase order item'), ('deactivate_purchase_order_item', 'Deactivate purchase order item'), ('delete_purchase_order_item', 'Delete purchase order item')],
                'default_permissions': [],
            },
        ),
    ]
