# Generated by Django 3.2.20 on 2024-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderrequestitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderrequestitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderrequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
