# Generated by Django 3.2.20 on 2024-01-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20240116_0721'),
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorderrequest',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequest',
            name='provider',
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderrequest',
            name='suppler_type',
            field=models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('STORE', 'STORE')], default='SUPPLIER', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderrequest',
            name='supplier_entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.supplier'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderrequest',
            name='supplier_store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.store'),
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='suppler_type',
            field=models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('STORE', 'STORE')], default='SUPPLIER', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='supplier_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='supplier_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_requests', to='company.store'),
        ),
    ]
