# Generated by Django 3.2.20 on 2024-01-29 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorderrequest',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequest',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderrequest',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 11, 23, 48, 75102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequest',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 11, 23, 48, 75102, tzinfo=utc)),
        ),
    ]
