# Generated by Django 3.2.20 on 2024-01-29 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20240129_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderrequest',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderrequest',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 11, 25, 15, 543349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequest',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 11, 25, 15, 543349, tzinfo=utc)),
        ),
    ]
