# Generated by Django 3.2.20 on 2024-01-29 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20240129_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorderrequest',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequest',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
