# Generated by Django 3.2.20 on 2024-01-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20240123_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorderrequestitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequestitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
