# Generated by Django 3.2.20 on 2024-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20240129_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderrequest',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
