# Generated by Django 3.2.20 on 2024-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20240131_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorderrequest',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequest',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderrequest',
            name='payment_period',
            field=models.CharField(choices=[('Instant', 'Instant'), ('After 7 days', 'After 7 days'), ('After 14 days', 'After 14 days'), ('After 30 days', 'After 30 days'), ('After 60 days', 'After 60 days')], default='Instant', max_length=25),
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='payment_period',
            field=models.CharField(choices=[('Instant', 'Instant'), ('After 7 days', 'After 7 days'), ('After 14 days', 'After 14 days'), ('After 30 days', 'After 30 days'), ('After 60 days', 'After 60 days')], default='Instant', max_length=25),
        ),
    ]
