# Generated by Django 3.2.20 on 2023-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_min_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
