# Generated by Django 3.2.20 on 2024-02-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreceivedstockitem',
            old_name='qty_received',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='receivedstockitem',
            old_name='qty_received',
            new_name='quantity',
        ),
    ]
