# Generated by Django 3.2.20 on 2024-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstock',
            name='delivered_by_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstock',
            name='delivered_by_phone',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstockitem',
            name='batch_no',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalstockitem',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalstockitem',
            name='unique_no',
            field=models.CharField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalvariant',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='delivered_by_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='delivered_by_phone',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='receivedstockitem',
            name='batch_no',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unique_no',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
