# Generated by Django 3.2.20 on 2024-01-10 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_store_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalProductType',
            new_name='HistoricalProductVariant',
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductVariant',
        ),
        migrations.AlterModelOptions(
            name='historicalproductvariant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical product variant', 'verbose_name_plural': 'historical product variants'},
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='type',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='variant',
        ),
    ]
