# Generated by Django 3.2.20 on 2024-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240414_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
