# Generated by Django 3.2.20 on 2024-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240130_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceivedstock',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstockrequest',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalstockrequest',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstockrequestitem',
            name='available_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalstockrequestitem',
            name='reason',
            field=models.CharField(choices=[('Low Stock', 'Low Stock'), ('New Product', 'New Product'), ('Other', 'Other')], default='Low Stock', max_length=225),
        ),
        migrations.AddField(
            model_name='receivedstock',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='available_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='reason',
            field=models.CharField(choices=[('Low Stock', 'Low Stock'), ('New Product', 'New Product'), ('Other', 'Other')], default='Low Stock', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalstockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalstockrequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=225),
        ),
        migrations.AlterField(
            model_name='stockrequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
