# Generated by Django 3.2.20 on 2024-01-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240110_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceivedstockitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receivedstockitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstockitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receivedstockitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
