# Generated by Django 3.2.20 on 2024-01-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240131_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedstock',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='receivedstockitem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='stockrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='stockrequestitem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ('-created_at',)},
        ),
    ]
