# Generated by Django 3.2.20 on 2024-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240414_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstockrequestitem',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='stockrequestitem',
            name='available_quantity',
        ),
        migrations.AlterField(
            model_name='historicalstockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=225),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=225),
        ),
    ]
