# Generated by Django 3.2.20 on 2024-01-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20240115_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
