# Generated by Django 3.2.20 on 2024-01-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240115_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstoreproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstoreproduct',
            name='item_photo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='item_photo',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
