# Generated by Django 3.2.20 on 2024-01-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20240115_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloutgoingconsumable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalreceivedstockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalstockrequestitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outgoingconsumable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='receivedstockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockrequestitem',
            name='product',
        ),
        migrations.AddField(
            model_name='historicaloutgoingconsumable',
            name='store_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.storeproduct'),
        ),
        migrations.AddField(
            model_name='historicalreceivedstockitem',
            name='store_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.storeproduct'),
        ),
        migrations.AddField(
            model_name='historicalstockrequestitem',
            name='store_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.storeproduct'),
        ),
        migrations.AddField(
            model_name='outgoingconsumable',
            name='store_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storeproduct'),
        ),
        migrations.AddField(
            model_name='receivedstockitem',
            name='store_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storeproduct'),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='store_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storeproduct'),
        ),
    ]
