# Generated by Django 3.2.20 on 2024-01-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20240115_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingconsumable',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeproduct'),
        ),
        migrations.AlterField(
            model_name='receivedstockitem',
            name='received_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.receivedstock'),
        ),
        migrations.AlterField(
            model_name='receivedstockitem',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeproduct'),
        ),
        migrations.AlterField(
            model_name='stockrequestitem',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storeproduct'),
        ),
    ]
