# Generated by Django 3.2.20 on 2024-01-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20240115_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloutgoingconsumable',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='historicalreceivedstock',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='historicalreceivedstockitem',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='historicalstockrequest',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='historicalstockrequestitem',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='outgoingconsumable',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='receivedstock',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='receivedstockitem',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='stockrequest',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='stockrequestitem',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.AddField(
            model_name='historicalreceivedstock',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='receivedstock',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10),
        ),
    ]
