# Generated by Django 3.2.20 on 2024-01-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20240115_1559'),
        ('inventory', '0010_auto_20240115_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstock',
            name='delivered_by_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstock',
            name='delivered_by_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreceivedstockitem',
            name='batch_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='delivered_by_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='delivered_by_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receivedstockitem',
            name='batch_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'company')},
        ),
    ]
