# Generated by Django 3.2.20 on 2024-01-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyapplication',
            name='status_type',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyapplication',
            name='status_type',
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcompanyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=255),
        ),
    ]
