# Generated by Django 3.2.20 on 2024-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylevelgroup',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanylevelgroup',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorelevelgroup',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='storelevelgroup',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
