# Generated by Django 3.2.20 on 2024-01-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20240130_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstore',
            old_name='status',
            new_name='status_type',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='status',
            new_name='status_type',
        ),
    ]
