# Generated by Django 3.2.20 on 2024-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20240103_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcompanyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=255),
        ),
    ]
