# Generated by Django 3.2.20 on 2024-02-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20240215_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': [], 'permissions': [('add_client', 'Add client'), ('list_client', 'List client'), ('view_client', 'View client'), ('edit_client', 'Edit client'), ('activate_client', 'Activate client'), ('deactivate_client', 'Deactivate client'), ('delete_client', 'Delete client')]},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': [], 'permissions': [('add_company', 'Add company'), ('list_company', 'List company'), ('view_company', 'View company'), ('edit_company', 'Edit company'), ('activate_company', 'Activate company'), ('deactivate_company', 'Deactivate company'), ('delete_company', 'Delete company')]},
        ),
        migrations.AlterModelOptions(
            name='companyapplication',
            options={'default_permissions': [], 'permissions': [('add_company', 'Add company'), ('list_company_application', 'List company application'), ('view_company_application', 'View company application'), ('edit_company_application', 'Edit company application'), ('approve_company_application', 'Approve company application'), ('decline_company_application', 'Decline company application'), ('cancel_company_application', 'Cancel company application'), ('activate_company_application', 'Activate company application'), ('deactivate_company_application', 'Deactivate company application'), ('delete_company_application', 'Delete company application')]},
        ),
        migrations.AlterModelOptions(
            name='companylevelgroup',
            options={'default_permissions': [], 'permissions': [('add_company_group', 'Add company group'), ('list_company_group', 'List company group'), ('view_company_group', 'View company group'), ('edit_company_group', 'Edit company group'), ('activate_company_group', 'Activate company group'), ('deactivate_company_group', 'Deactivate company group'), ('delete_company_group', 'Delete company group')]},
        ),
        migrations.AlterModelOptions(
            name='poscenter',
            options={'default_permissions': [], 'permissions': [('add_pos_center', 'Add pos center'), ('list_pos_center', 'List pos center'), ('view_pos_center', 'View pos center'), ('edit_pos_center', 'Edit pos center'), ('activate_pos_center', 'Activate pos center'), ('deactivate_pos_center', 'Deactivate pos center'), ('delete_pos_center', 'Delete pos center')]},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': [], 'permissions': [('add_store', 'Add store'), ('list_store', 'List store'), ('view_store', 'View store'), ('edit_store', 'Edit store'), ('activate_store', 'Activate store'), ('deactivate_store', 'Deactivate store'), ('delete_store', 'Delete store')]},
        ),
        migrations.AlterModelOptions(
            name='storelevelgroup',
            options={'default_permissions': [], 'permissions': [('add_company_group', 'Add company group'), ('list_company_group', 'List company group'), ('view_company_group', 'View company group'), ('edit_company_group', 'Edit company group'), ('activate_company_group', 'Activate company group'), ('deactivate_company_group', 'Deactivate company group'), ('delete_company_group', 'Delete company group')]},
        ),
        migrations.AlterModelOptions(
            name='supplierentity',
            options={'default_permissions': [], 'permissions': [('add_supplier_entity', 'Add supplier entity'), ('list_supplier_entity', 'List supplier entity'), ('view_supplier_entity', 'View supplier entity'), ('edit_supplier_entity', 'Edit supplier entity'), ('activate_supplier_entity', 'Activate supplier entity'), ('deactivate_supplier_entity', 'Deactivate supplier entity'), ('delete_supplier_entity', 'Delete supplier entity')]},
        ),
    ]
