# Generated by Django 3.2.20 on 2024-02-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20240220_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyapplication',
            options={'default_permissions': [], 'permissions': [('add_company_application', 'Add company application'), ('list_company_application', 'List company application'), ('view_company_application', 'View company application'), ('edit_company_application', 'Edit company application'), ('approve_company_application', 'Approve company application'), ('decline_company_application', 'Decline company application'), ('cancel_company_application', 'Cancel company application'), ('activate_company_application', 'Activate company application'), ('deactivate_company_application', 'Deactivate company application'), ('delete_company_application', 'Delete company application')]},
        ),
        migrations.AlterModelOptions(
            name='storelevelgroup',
            options={'default_permissions': [], 'permissions': [('add_store_group', 'Add store group'), ('list_store_group', 'List store group'), ('view_store_group', 'View store group'), ('edit_store_group', 'Edit store group'), ('activate_store_group', 'Activate store group'), ('deactivate_store_group', 'Deactivate store group'), ('delete_store_group', 'Delete store group')]},
        ),
    ]
