# Generated by Django 3.2.20 on 2024-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20240226_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='companyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CREATED', 'CREATED'), ('DECLINED', 'DECLINED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CREATED', 'CREATED'), ('DECLINED', 'DECLINED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalstore',
            name='status_type',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalstore',
            name='store_type',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('WHOLESALE', 'WHOLESALE')], max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalsupplierentity',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='store',
            name='status_type',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=225),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('WHOLESALE', 'WHOLESALE')], max_length=225),
        ),
        migrations.AlterField(
            model_name='supplierentity',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
