# Generated by Django 3.2.20 on 2024-01-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_store_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstore',
            old_name='status_type',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='status_type',
            new_name='status',
        ),
    ]
