# Generated by Django 3.2.20 on 2024-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20240104_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='store',
            name='location_district',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location_village',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalStore',
        ),
    ]
