# Generated by Django 3.2.20 on 2024-01-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_store_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsupplierentity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalsupplierentity',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='historicalsupplierentity',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalsupplierentity',
            name='updated_by_id',
        ),
        migrations.RemoveField(
            model_name='supplierentity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplierentity',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='supplierentity',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplierentity',
            name='updated_by_id',
        ),
        migrations.AddField(
            model_name='historicalsupplierentity',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplierentity',
            name='phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplierentity',
            name='updated_by',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='supplierentity',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='supplierentity',
            name='phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='supplierentity',
            name='updated_by',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
