# Generated by Django 3.2.20 on 2024-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20240110_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprovider',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.AlterField(
            model_name='historicalprovider',
            name='provider_type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('STORE', 'Store')], default='Supplier', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('STORE', 'Store')], default='Supplier', max_length=10),
        ),
    ]
