# Generated by Django 3.2.20 on 2024-01-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20240110_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='historicalcustomer',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.AddField(
            model_name='historicalsupplierentity',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='supplierentity',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
