# Generated by Django 3.2.20 on 2024-01-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20240110_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprovider',
            name='provider_type',
            field=models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('STORE', 'STORE')], default='SUPPLIER', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('STORE', 'STORE')], default='SUPPLIER', max_length=10),
        ),
    ]
