# Generated by Django 3.2.20 on 2024-01-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20240116_0721'),
        ('purchases', '0003_auto_20240116_0721'),
        ('company', '0016_auto_20240116_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
