# Generated by Django 3.2.20 on 2024-01-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
