# Generated by Django 3.2.20 on 2024-02-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'default_permissions': [], 'permissions': [('list_user_profile', 'List user profile'), ('view_user_profile', 'View user profile'), ('add_user_profile', 'Add user profile'), ('edit_user_profile', 'Edit user profile'), ('assign_company', 'Assign company'), ('unassign_company', 'Unassign company'), ('assign_store', 'Assign store'), ('unassign_store', 'Unassign store'), ('assign_pos_center', 'Assign pos center'), ('unassign_pos_center', 'Unassign pos center'), ('activate_user_profile', 'Activate user profile'), ('deactivate_user_profile', 'Deactivate user profile'), ('delete_user_profile', 'Delete user profile')]},
        ),
    ]
