# Generated by Django 3.2.20 on 2023-12-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231207_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDirector',
            new_name='CompanyAdmin',
        ),
    ]
