# Generated by Django 3.2.20 on 2024-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_auto_20240103_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='account_type',
            field=models.CharField(choices=[('App Admin', 'App Admin'), ('Company Admin', 'Company Admin'), ('Store Admin', 'Store Admin'), ('POS Attendant', 'POS Attendant')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('App Admin', 'App Admin'), ('Company Admin', 'Company Admin'), ('Store Admin', 'Store Admin'), ('POS Attendant', 'POS Attendant')], max_length=255),
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('App Admin', 'App Admin'), ('Company Admin', 'Company Admin'), ('Store Admin', 'Store Admin'), ('POS Attendant', 'POS Attendant')], max_length=225)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
