# Generated by Django 3.2.20 on 2023-12-07 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_companydirector_companyadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='company_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companybranch'),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companybranch'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
        migrations.CreateModel(
            name='CompanyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by_id', models.CharField(blank=True, max_length=225, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('company_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companybranch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers_createdby', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
