# Generated by Django 3.2.20 on 2024-01-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_store_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_auto_20240104_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.companygroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'unique_together': {('company_group', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='companygroup',
            name='permissions',
            field=models.ManyToManyField(through='user.CompanyGroupPermission', to='auth.Permission'),
        ),
        migrations.AlterUniqueTogether(
            name='companygroup',
            unique_together={('group', 'company')},
        ),
    ]
