# Generated by Django 3.2.20 on 2024-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='account_type',
            field=models.CharField(choices=[('App Admin', 'App Admin'), ('Company Admin', 'Company Admin'), ('Store Admin', 'Store Admin'), ('POS Attendant', 'POS Attendant')], max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('App Admin', 'App Admin'), ('Company Admin', 'Company Admin'), ('Store Admin', 'Store Admin'), ('POS Attendant', 'POS Attendant')], max_length=225),
        ),
    ]
