# Generated by Django 3.2.20 on 2024-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE'), ('PAID', 'PAID')], default='PAID', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='payment_terms',
            field=models.CharField(choices=[('Instant', 'Instant'), ('7 days', '7 days'), ('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='Instant', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE'), ('PAID', 'PAID')], default='PAID', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_terms',
            field=models.CharField(choices=[('Instant', 'Instant'), ('7 days', '7 days'), ('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='Instant', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_option',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Airtel MOney', 'Airtel MOney'), ('MTN MOney', 'MTN MOney'), ('Cheque', 'Cheque')], default='Cash', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Completed', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_option',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Airtel MOney', 'Airtel MOney'), ('MTN MOney', 'MTN MOney'), ('Cheque', 'Cheque')], default='Cash', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Completed', max_length=10),
        ),
    ]
