# Generated by Django 3.2.20 on 2024-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
