# Generated by Django 3.2.20 on 2024-01-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsaleitem',
            name='pos_center',
        ),
        migrations.RemoveField(
            model_name='historicalsaleitem',
            name='price_sold',
        ),
        migrations.RemoveField(
            model_name='historicalsaleitem',
            name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='pos_center',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price_sold',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity_sold',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='pos_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.poscenter'),
        ),
        migrations.AddField(
            model_name='historicalsaleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalsaleitem',
            name='sale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='historicalsaleitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalsaleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='pos_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.poscenter'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
