# Generated by Django 3.2.20 on 2024-01-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('sales', '0003_auto_20240124_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='pos_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.poscenter'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
