# Generated by Django 3.2.20 on 2024-01-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoicefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceFile',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='invoice_file',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_file',
            field=models.FileField(null=True, upload_to='invoices'),
        ),
    ]
