# Generated by Django 3.2.20 on 2024-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20240124_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='company',
        ),
        migrations.RenameField(
            model_name='historicalsale',
            old_name='updated_by_id',
            new_name='payment_details',
        ),
        migrations.RenameField(
            model_name='historicalsaleitem',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='updated_by_id',
            new_name='payment_details',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='updated_by_id',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='payment_option',
            field=models.CharField(choices=[('Cash', 'Casn'), ('Airtel MOney', 'Airtel MOney'), ('MTN MOney', 'MTN MOney'), ('Cheque', 'Cheque')], default='Casn', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='updated_by',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_option',
            field=models.CharField(choices=[('Cash', 'Casn'), ('Airtel MOney', 'Airtel MOney'), ('MTN MOney', 'MTN MOney'), ('Cheque', 'Cheque')], default='Casn', max_length=25),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_by',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
