# Generated by Django 3.2.20 on 2024-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20240131_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsale',
            old_name='sale_remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sale_remarks',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE')], default='PAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE')], default='PAID', max_length=10),
        ),
    ]
