# Generated by Django 3.2.20 on 2024-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20240201_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE')], default='PAID', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_terms',
            field=models.CharField(choices=[('Instant', 'Instant'), ('After 7 days', 'After 7 days'), ('After 14 days', 'After 14 days'), ('After 30 days', 'After 30 days'), ('After 60 days', 'After 60 days')], default='Instant', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Completed', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE')], default='PAID', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_terms',
            field=models.CharField(choices=[('Instant', 'Instant'), ('After 7 days', 'After 7 days'), ('After 14 days', 'After 14 days'), ('After 30 days', 'After 30 days'), ('After 60 days', 'After 60 days')], default='Instant', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Completed', max_length=25),
        ),
    ]
