# Generated by Django 3.2.20 on 2024-02-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20240201_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsale',
            old_name='payment_terms',
            new_name='payment_period',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='payment_terms',
            new_name='payment_period',
        ),
    ]
